spring:
  profiles:
    active:
    - dev
---
server:
  port: 8092
spring:
  profiles: dev
  application:
    name: config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@eureka:8083/eureka/
    register-with-eureka: true

---
server:
  port: 8093
spring:
  profiles: test
  application:
    name: microservicecloud-test
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@eureka:8083/eureka/
    register-with-eureka: true
