spring:
  profiles:
    active:
    - dev
---
server:
  port: 8092
spring:
  profiles: dev
  application:
    name: microservicecloud-dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8083/eureka/
    register-with-eureka: false

---
server:
  port: 8093
spring:
  profiles: test
  application:
    name: microservicecloud-test
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8083/eureka/
    register-with-eureka: false